<a href="https://colab.research.google.com/github/amgothhrithik/Logistic_Regression/blob/main/Logistic_regression_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
import pandas as pd
file_path = '/content/drive/My Drive/Data/iris/iris.data'

# Read the CSV file
df = pd.read_csv(file_path,names=["sepal_len","sepal_width","petal_len","petal_width","type"])
#df.reset_index(inplace=True)
iris = 'output.csv'
df.to_csv(iris, index=True)
# Display the first few rows of the DataFrame
df.head()


sepal_len  sepal_width  petal_len  petal_width         type
0        5.1          3.5        1.4          0.2  Iris-setosa
1        4.9          3.0        1.4          0.2  Iris-setosa
2        4.7          3.2        1.3          0.2  Iris-setosa
3        4.6          3.1        1.5          0.2  Iris-setosa
4        5.0          3.6        1.4          0.2  Iris-setosa

In [ ]:
df= pd.get_dummies(df, columns=['type'])
bool_cols = df.select_dtypes(include=['bool']).columns
df[bool_cols] = df[bool_cols].astype(int)
df.sample(5)

sepal_len  sepal_width  petal_len  petal_width  type_Iris-setosa  \
0          5.1          3.5        1.4          0.2                 1   
82         5.8          2.7        3.9          1.2                 0   
142        5.8          2.7        5.1          1.9                 0   
42         4.4          3.2        1.3          0.2                 1   
135        7.7          3.0        6.1          2.3                 0   

     type_Iris-versicolor  type_Iris-virginica  
0                       0                    0  
82                      1                    0  
142                     0                    1  
42                      0                    0  
135                     0                    1

In [ ]:
x=df.iloc[:,0:4]
y=df.iloc[:,4:]


In [ ]:
import numpy as np
import random
x=np.array(x)
x= np.concatenate((np.ones((len(x), 1)), x),axis=1)
y=np.array(y)
m=np.random.permutation(len(x))
x=x[m]
y=y[m]

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,  y, test_size=0.2, random_state=42)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(x_train)
x_train= scaler.fit_transform(x_train)
x_test= scaler.fit_transform(x_test)

In [ ]:
class Classiifcation_FBGD:
  def __init__(self,epochs,lr):
    self.epochs=epochs
    self.lr=lr
    self.w=None
  def Loss(self,y,y1):
    return -np.sum(y*np.log(y1))

  def softmax(self,z):
    exp_z = np.exp(z - np.max(z, axis=1, keepdims=True))  # Stability trick
    return exp_z / np.sum(exp_z, axis=1, keepdims=True)

  def fit(self,x,y):
    L=[]
    interval=self.epochs//10
    self.w=np.random.randn(x.shape[1],y.shape[1])*(1/np.sqrt(x.shape[1]))
    for epoch in range(self.epochs):

      z=np.dot(x,self.w)
      y_pred=self.softmax(z)
      residual=y_pred-y
      gradient=np.matmul(x.T,residual)/len(y)
      self.w-=self.lr*gradient
      l=self.Loss(y,y_pred)
      L.append(l)
      if epoch % interval== 0:
        print(f"Epoch {epoch}, Loss: {l}")

    return L,self.w
  def predict(self,x):
    z=np.dot(x,self.w)
    return self.softmax(z)

In [ ]:
epochs=5000
lr=0.3
model=Classiifcation_FBGD(epochs,lr)
l,w=model.fit(x_train,y_train)
y_pred=model.predict(x_test)

Epoch 0, Loss: 107.64761618441511
Epoch 500, Loss: 38.13840758989626
Epoch 1000, Loss: 37.34672148270144
Epoch 1500, Loss: 37.007242065094815
Epoch 2000, Loss: 36.8131140560871
Epoch 2500, Loss: 36.68419141274186
Epoch 3000, Loss: 36.590507224477946
Epoch 3500, Loss: 36.51837707331733
Epoch 4000, Loss: 36.46060606079381
Epoch 4500, Loss: 36.41299641190423


In [ ]:
y_pred = (y_pred > 0.5).astype(int)
#print(y_pred)
c=0
for i in range(len(y_test)):
  if np.array_equal(y_test[i], y_pred[i])==True:
    c+=1
print(c/len(y_test)*100)

90.0


In [ ]:
print(y_test)

[[0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]
